version: "3"
services:

  app:
    image: aemartinez/dds-inversiones:0.1
    networks:
      - network-db-rel
      - network-db-doc
      - network-cache
    volumes:
      - .:/apptr
      - ./dependencies:/root/.m2/repository
    ports:
      - 21000:8080
    depends_on:
      - db-rel
      - db-doc
      - cache


  #DB----------------------------------------------------------------------------------------------
  db-rel:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - network-db-rel
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d


  db-doc:
    image: mongo
    networks:
      - network-db-doc
    volumes:
      - mongo-data:/data/db


  #Cache-------------------------------------------------------------------------------------------
  cache:
    image: redis
    networks:
      - network-cache


  #DB UI-------------------------------------------------------------------------------------------
  db-rel-ui:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db-rel
    networks:
      - network-db-rel
    depends_on:
      - db-rel


  db-doc-ui:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db-doc
    networks:
      - network-db-doc
    depends_on:
      - db-doc


volumes:
  mysql-data:
  mongo-data:


networks:
  network-cache:
    driver: bridge
  network-db-rel:
    driver: bridge
  network-db-doc:
    driver: bridge