version: "3"
services:

  app:
    build:
      context: .
    links:
      - db-rel
      - db-doc
      - cache
    volumes:
      - .:/app
      - ./dependencies:/root/.m2/repository

    ports:
      - 21000:8080


  #DB----------------------------------------------------------------------------------------------
  db-rel:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql

#    ports:
#      - 3306:3306


  db-doc:
    image: mongo
    volumes:
      - mongo-data:/data/db

#    ports:
#      - 27017:27017


  #Cache-------------------------------------------------------------------------------------------
  cache:
    image: redis

#    ports:
#      - 6379:6379


  #DB UI-------------------------------------------------------------------------------------------
  db-rel-ui:
    image: phpmyadmin/phpmyadmin
    links:
      - db-rel:db

    ports:
      - 20000:80


  db-doc-ui:
    image: mongo-express
    links:
      - db-doc:mongo

    ports:
      - 20001:8081


volumes:
  mysql-data:
  mongo-data: