CREATE DATABASE INVERSIONES;

USE INVERSIONES;

CREATE TABLE EMPRESA (
	empresa_id INT NOT NULL AUTO_INCREMENT,
	empresa_nombre VARCHAR(255) NOT NULL,
	CONSTRAINT PK_EMPRESA_ID PRIMARY KEY (empresa_id)
);

CREATE TABLE PERIODO (
	periodo_id INT NOT NULL AUTO_INCREMENT,
	fecha_inicio DATE NOT NULL,
	fecha_fin DATE NOT NULL,
	CONSTRAINT PK_PERIODO_ID PRIMARY KEY (periodo_id)
);

CREATE TABLE CUENTA (
	cuenta_id INT NOT NULL AUTO_INCREMENT,
	cuenta_nombre VARCHAR(255) NOT NULL,
	cuenta_valor DOUBLE PRECISION NOT NULL,
	CONSTRAINT PK_CUENTA_ID PRIMARY KEY (cuenta_id)
);

CREATE TABLE CUENTA_PERIODO (
	cp_id INT NOT NULL AUTO_INCREMENT,
	cp_periodo_id INT NOT NULL,
	cp_cuenta_id INT NOT NULL,
	CONSTRAINT PK_CP_ID PRIMARY KEY (cp_id)
);

CREATE TABLE PERIODO_EMPRESA (
	pe_id INT NOT NULL AUTO_INCREMENT,
	pe_empresa_id INT NOT NULL,
	pe_periodo_id INT NOT NULL,
	CONSTRAINT PK_PE_ID PRIMARY KEY (pe_id)
);

ALTER TABLE CUENTA_PERIODO ADD CONSTRAINT FK_CP_CUENTA FOREIGN KEY (cp_cuenta_id) REFERENCES CUENTA(cuenta_id);
ALTER TABLE CUENTA_PERIODO ADD CONSTRAINT FK_CP_PERIODO FOREIGN KEY (cp_periodo_id) REFERENCES PERIODO(periodo_id);
ALTER TABLE PERIODO_EMPRESA ADD CONSTRAINT FK_PE_PERIODO FOREIGN KEY (pe_periodo_id) REFERENCES PERIODO(periodo_id);
ALTER TABLE PERIODO_EMPRESA ADD CONSTRAINT FK_PE_EMPRESA FOREIGN KEY (pe_empresa_id) REFERENCES EMPRESA(empresa_id);